[package]
name = "complewise_iter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gat-lending-iterator = "=0.1.2"
criterion = "*"

[[bench]]
name = "my_benchmark"
harness = false